# Site
name: 'News Terminal Root'
description: 'A reunião das melhores publicações da internet estão aqui.'
logo: 'assets/images/favicon.png'
favicon: 'assets/images/favicon.png'
baseurl: '/news/'
source: news
disqus: 'disqus_o9Wbt23Bfs'
email: 'terminalroottv@gmail.com'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title.html

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    sal:
      name:           Marcos
      site:           https://news.terminalroot.com.br
      avatar:         assets/images/avatar.png
      bio:            "Redator"
      email:          contato@terminalroot.com.br
      twitter:        https://twitter.com/TerminalRootTV

    jane:
      name:           Marcos
      site:           https://news.terminalroot.com.br
      avatar:         assets/images/avatar.png
      bio:            "Redator"
      email:          contato@terminalroot.com.br
      twitter:        https://twitter.com/TerminalRootTV
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: jane
      avatar: assets/images/avatar2.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
